name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: now-sdk-builder
        tags: latest ${{ github.sha }}
        context: .
        containerfiles: |
          ./Dockerfile

    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Push To Quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/vlpl
        username: vlpl+gh_actions
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Log
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
